[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
arrayvec.workspace = true
num.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
